[tool.poetry]
name = "CLI-Importer"
version = "3.0"
description = ""
authors = ["Arne Boockmeyer <arne.boockmeyer@hpi.de>"]
packages = [{include = "cli_importer"}]

[tool.poetry.dependencies]
python = "^3.11"
yaramo = {git = "https://github.com/simulate-digital-rail/yaramo", branch = "yaramo2" }
railway-route-generator = {git = "https://github.com/simulate-digital-rail/railway-route-generator", branch = "yaramo2" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
